TRANSLATIONS = {
    'en': {
        'menu_title': 'Select Difficulty',
        'easy': 'Easy',
        'medium': 'Medium',
        'hard': 'Hard',
        'difficulty': 'Difficulty',
        'time': 'Time',
        'collected': 'Collected',
        'controls_keyboard': 'Controls: WASD to move',
        'controls_controller': 'Controls: Left Stick to move, X to interact',
        'game_over': 'Game Over!',
        'time_up': "Time's Up!",
        'caught_by_boss': 'Caught by a Boss!',
        'press_to_restart': 'Press ENTER or X to restart',
        'escape_success': 'Escape Successful!',
        'question': 'Where is the headquarters of Weidmüller?',
        'select_language': 'Select Language',
        'press_to_select': 'Press ENTER or X to select',
        'language_name': 'English',
        'next_letter': 'Next Letter',
        'select_character': 'Select your Character',
        'character_jonas': 'Jonas',
        'character_robert': 'Robert', 
        'character_sebastian': 'Sebastian'
    },
    'de': {
        'menu_title': 'Schwierigkeitsgrad wählen',
        'easy': 'Einfach',
        'medium': 'Mittel',
        'hard': 'Schwer',
        'difficulty': 'Schwierigkeit',
        'time': 'Zeit',
        'collected': 'Gesammelt',
        'controls_keyboard': 'Steuerung: WASD zum Bewegen',
        'controls_controller': 'Steuerung: Linker Stick zum Bewegen, X für Interaktion',
        'game_over': 'Spiel vorbei!',
        'time_up': 'Zeit abgelaufen!',
        'caught_by_boss': 'Von einem Boss gefangen!',
        'press_to_restart': 'ENTER oder X zum Neustart drücken',
        'escape_success': 'Flucht erfolgreich!',
        'question': 'Wo ist der Hauptsitz von Weidmüller?',
        'select_language': 'Sprache wählen',
        'press_to_select': 'ENTER oder X zum Auswählen drücken',
        'language_name': 'Deutsch',
        'next_letter': 'Nächster Buchstabe',
        'select_character': 'Wähle deinen Charakter',
        'character_jonas': 'Jonas',
        'character_robert': 'Robert',
        'character_sebastian': 'Sebastian'
    }
}
