TRANSLATIONS = {
    'en': {
        'menu_title': 'Main Menu',
        'easy': 'Easy',
        'medium': 'Medium',
        'hard': 'Hard',
        'difficulty': 'Difficulty',
        'time': 'Time',
        'collected': 'Collected',
        'controls_keyboard': 'Controls: WASD to move',
        'controls_controller': 'Controls: Left Stick to move, X to interact',
        'game_over': 'Game Over',
        'time_up': 'Time is up!',
        'caught_by_boss': 'Caught by Boss!',
        'press_to_restart': 'Press ENTER or X button to restart',
        'escape_success': 'Escape Successful!',
        'question': 'Where is the headquarters of Weidmüller?',
        'select_language': 'Select Language',
        'press_to_select': 'Press ENTER to select',
        'press_x_to_select': 'Press X button to select',
        'language_name': 'English',
        'next_letter': 'Next Letter',
        'select_character': 'Select Character',
        'character_jonas': 'Jonas',
        'character_robert': 'Robert', 
        'character_sebastian': 'Sebastian',
        'select_difficulty': 'Select Difficulty',
        'victory': 'Victory!',
        'time_left': 'Time left: ',
        'caught': 'You were caught!',
        'you_won': 'Congratulations!',
        'answer': 'The answer is:'
    },
    'de': {
        'menu_title': 'Hauptmenü',
        'easy': 'Einfach',
        'medium': 'Mittel',
        'hard': 'Schwer',
        'difficulty': 'Schwierigkeit',
        'time': 'Zeit',
        'collected': 'Gesammelt',
        'controls_keyboard': 'Steuerung: WASD zum Bewegen',
        'controls_controller': 'Steuerung: Linker Stick zum Bewegen, X für Interaktion',
        'game_over': 'Spiel vorbei',
        'time_up': 'Zeit abgelaufen!',
        'caught_by_boss': 'Vom Boss erwischt!',
        'press_to_restart': 'ENTER oder X-Taste zum Neustart',
        'escape_success': 'Flucht erfolgreich!',
        'question': 'Wo ist der Hauptsitz von Weidmüller?',
        'select_language': 'Sprache wählen',
        'press_to_select': 'ENTER zum Auswählen',
        'press_x_to_select': 'X-Taste zum Auswählen',
        'language_name': 'Deutsch',
        'next_letter': 'Nächster Buchstabe',
        'select_character': 'Charakter wählen',
        'character_jonas': 'Jonas',
        'character_robert': 'Robert',
        'character_sebastian': 'Sebastian',
        'select_difficulty': 'Schwierigkeit wählen',
        'victory': 'Gewonnen!',
        'time_left': 'Verbleibende Zeit: ',
        'caught': 'Du wurdest gefangen!',
        'you_won': 'Glückwunsch!',
        'answer': 'Die Antwort ist:'
    }
}
